### ISSUE TITLE
No matching distribution found for causal-conv1d==1.2.0

### ISSUE THREAD

**Issue by 1having0** [SkyworkAI/Gamba#2]
I used python 3.8, but when I 'pip install causal-conv1d==1.2.0 mamba-ssm' , I got the following errors. How can I solve?

ERROR: Could not find a version that satisfies the requirement causal-conv1d==1.2.0 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2.post1, 1.1.3.post1, 1.2.0.post1, 1.2.0.post2, 1.2.1, 1.2.2.post1, 1.3.0.post1, 1.4.0)
ERROR: No matching distribution found for causal-conv1d==1.2.0

**Comment by florinshen** [comment]
As this project is built on mamba-v1, the installation of causal-conv1d package is not mandatory
