### ISSUE TITLE
which version of mamba_ssm should I install？

### ISSUE THREAD

**Issue by 1having0** [SkyworkAI/Gamba#3]

**Comment by 1having0** [comment]
from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn
ModuleNotFoundError: No module named 'mamba_ssm.ops.triton.layernorm'

**Comment by florinshen** [comment]
The mamba-ssm package used in this project is v1.2.2, you may check this download link of pre-compiled wheels. https://github.com/state-spaces/mamba/releases/download/v1.2.2/mamba_ssm-1.2.2+cu118torch2.1cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
